### ISSUE TITLE
Error: [wildcard] query does not support [case_insensitive]

### ISSUE THREAD

**Issue by oortalabelgrup** [Jeroen-G/Explorer#147]
After adding 'case_insensitive' in release 3.3 (file: src/Domain/Syntax/Wildcard.php) I get this error: [wildcard] query does not support [case_insensitive]

I'm using elastic 7.9.3

**Comment by Jeroen-G** [comment]
Check the ES docs if your version supports that parameter, I don't know to be honest.

**Comment by oortalabelgrup** [comment]
The parameter can be used from version 7.10. I am using the version that is indicated in the Explorer documentation (7.9.3), in Quickstart. Could you tell me which version is appropriate to use with your package?
Thanks!

**Comment by Jeroen-G** [comment]
Elastic is so huge and with so many options, I am not always sure. If the upgrade to 7.10 is not to hard for you I'd say that newer is better.

I will think of a way to put that case insensitive feature behind a feature flag check of some kind. And in the future I should better check which ES versions a given feature supports, because 7.9 should work fine with Explorer.

**Comment by oortalabelgrup** [comment]
I tested it with version 7.10 and it works. Additionally, I have updated my project to version 7.17.8 without any problems.

**Comment by blackshadev** [comment]
Closing this issue, since you resolved this by updating. 

Making syntax nodes differ between elastic versions seems excessive. 

If someone wants to support other or older elastic query nodes, one can easily extend the syntax interface and add them in there own package. 

Maybe this will change in the future if a lot of people want other behavior depending on the elastic version, if so, feel free to speak up (or create an PR)
